add pre push

diff --git a/frontend/.husky/pre-push b/frontend/.husky/pre-push
--- a/frontend/.husky/pre-push
+++ b/frontend/.husky/pre-push
@@ -2,10 +2,10 @@
 . "$(dirname "$0")/_/husky.sh"
 
 echo "Running ESLint..."
-npx eslint . --max-warnings=0 || exit 1  # Stop push if ESLint errors exist
+cd frontend && npx eslint . --max-warnings=0 || exit 1  # Ensures failure on errors
 
 echo "Running Prettier..."
-npx prettier --write frontend --ignore-path .prettierignore || exit 1  # Stop push if Prettier fails
+npx prettier --write . --ignore-path .prettierignore || exit 1  # Stop push if Prettier fails
 
 echo "Building Project with pnpm..."
 pnpm run build || exit 1  # Stop push if build fails
